# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
            args: [--line-length=100, --exclude=""]
    # ----
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v1.3.0"
      hooks:
          - id: mypy
            args: ["--config-file=mypy.ini", "--no-site-packages"]

      # this is not technically always safe but usually is
      # use comments `# isort: off` and `# isort: on` to disable/re-enable isort
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: [--line-length=100, --profile=black]

      # this is slightly dangerous because python imports have side effects
      # and this tool removes unused imports, which may be providing
      # necessary side effects for the code to run
    - repo: https://github.com/PyCQA/autoflake
      rev: v1.6.1
      hooks:
          - id: autoflake
            args:
                - "--in-place"
                - "--expand-star-imports"
                - "--remove-duplicate-keys"
                - "--remove-unused-variables"
                - "--remove-all-unused-imports"

      # This allows ruff to run and autofix the code
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.0.277
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix, --line-length=100]
